### ISSUE TITLE
Revit switches to interactive mode if model is saved in perspective view

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/DynamoAutomation#12]
If a model was saved in a perspective view the following happens: The script will execute but Revit subsequently will switch into interactive mode, which means the batch process will be interrupted until Revit is manually closed.

There is no fix for this as this is a Revit issue.

**Comment by kronz** [comment]
@andydandy74 I think what is happening is that you are getting the same thing as when you try and start a plugin through the UI when in Perspective, it's greyed out/unavailable.  Can you try adding this to the journal script after initial startup?
Jrn.Command "Ribbon" , "Create a default 3D orthographic view. , ID_VIEW_DEFAULT_3DVIEW"

This should pop ANY loaded file into an editable view, and thereby enable the addin tab

fyi @ikeough

**Comment by andydandy74** [comment]
This is probably not an issue after 2017.1 - need to test.

**Comment by andydandy74** [comment]
Documented here: https://github.com/andydandy74/DynamoAutomation#requirements
