### ISSUE TITLE
Dynamo Automation - Journal Issue

### ISSUE THREAD

**Issue by kiknchikn2060** [andydandy74/DynamoAutomation#19]
### Description
Upon running the master graph, Revit opens and this message appears -
![dyno1](https://cloud.githubusercontent.com/assets/23665914/20541611/06465954-b0cc-11e6-834e-19023bd18369.png). The dialog box has to be closed along with Revit. This continues until all slave graphs are ran. Once Dynamo completes the run, the journals are created. 
![help10](https://cloud.githubusercontent.com/assets/23665914/20541881/f4c2ba14-b0cc-11e6-9318-03eab1bc23cf.png) This is the master graph
![help11](https://cloud.githubusercontent.com/assets/23665914/20542624/65e8c3e8-b0d0-11e6-902e-e94ab1e897ad.png)

### Expected behaviour
The script is suppose to run a slave script editing multiple families at once. 

### My setup
- Operating System: Windows 7
- Dynamo version: 1.2
- Revit version & build number: Version:2015 Build Number:20160512_1515(x64)

### Housekeeping

Please **make sure these boxes are checked** before submitting your issue:
- [*] I am running the *latest* DynamoAutomation version
- [*] I am running a stable 1.x build of Dynamo (no dialy build)
- [*] I am using Revit 2015 or higher
- [*] I do not have multiple Dynamo versions installed on my system
- [*] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [*] None of the Revit models in my setup open with a warning
- [*] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
Your slave graph file name contains whitespaces, doesn't it?

**Comment by kiknchikn2060** [comment]
You know you are correct sir. Sorry about that. I should have paid more attention.

**Comment by andydandy74** [comment]
@kiknchikn2060 sorry for not following up.
Did you get this resolved on your own or have you given up on it?
Have you tried running it on top of Revit 2016?

**Comment by andydandy74** [comment]
Closing this - please feel free to re-open

**Comment by kempcao** [comment]
Could anyone tell me why there is no Journal.ByWorksapcePath node and Process.BypathAndArgument node in the latest package? I downloaded the package but couldn't find them. Really thanks!
