### ISSUE TITLE
Project opens but does not save

### ISSUE THREAD

**Issue by DavidAFink** [andydandy74/DynamoAutomation#20]
### Description
When running the master graph the project is opened and closed but the project is not saved and I am uncertain if the slave graph is being executed. I am running the master graph from Dynamo Studio 2017

### Expected behaviour
(Please fill in)

### My setup
- Operating System: Windows 7 64 bit
- Dynamo version: 1.2
- Revit version & build number: 2016 16.0.1161.0 20160720_0715(x64) Update 6 for R2
2015 20160512_0715(x64) Update 14

[Dynamo_Journal_File_1.txt](https://github.com/andydandy74/DynamoAutomation/files/617541/Dynamo_Journal_File_1.txt)
[journal.0001.txt](https://github.com/andydandy74/DynamoAutomation/files/617542/journal.0001.txt)

[Dynamo_Journal_File_1.txt](https://github.com/andydandy74/DynamoAutomation/files/617547/Dynamo_Journal_File_1.txt)
[journal.0001.txt](https://github.com/andydandy74/DynamoAutomation/files/617548/journal.0001.txt)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *latest* DynamoAutomation version
- [ ] I am running a stable 1.x build of Dynamo (no dialy build)
- [ ] I am using Revit 2015 or higher
- [ ] I do not have multiple Dynamo versions installed on my system
- [ ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [ ] None of the Revit models in my setup open with a warning
- [ ] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@DavidAFink - Please try this solution under Dynamo 1.3:
https://github.com/andydandy74/DynamoAutomation/issues/27#issuecomment-302294506

**Comment by andydandy74** [comment]
continued in #27
