### ISSUE TITLE
Open Central Files in "local mode" and save as local copy during execution of master graph

### ISSUE THREAD

**Issue by denerlich** [andydandy74/DynamoAutomation#21]
### Description

Revit Models participating in Dynamo Automation are Central Models with work sets.
Currently, central models are being evoked by Master Graph, prompting user to open "Enter Interactive mode" 

### Expected behaviour
Dynamo master automation graph will evoke Revit in such a manner, that Revit will open model files in "local/detached" mode and save models with the name inherited from the "Central" Revit file, but locally, preserving work sets.

### My setup
- Operating System: Windows 7
- Dynamo version: 1.2.1
- Revit version & build number: .2015 & 20140223_1515(x64)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [V ] I am running the *latest* DynamoAutomation version
- [V ] I am running a stable 1.x build of Dynamo (no dialy build)
- [V ] I am using Revit 2015 or higher
- [V ] I do not have multiple Dynamo versions installed on my system
- [V ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [V ] None of the Revit models in my setup open with a warning
- [V ] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
I already created an issue for opening detached (#16).
I'll check if I can add some more options to Clockwork's ````Document.SaveAs``` node to support saving as a new central file (https://github.com/andydandy74/ClockworkForDynamo/issues/126).

**Comment by denerlich** [comment]
Much appreciated!



With Regards,

Denis Erlich

BIM Manager Design-Build
Crosslinx Transit Solutions - Constructors
Tel.: 416-252-5315 Ext. 52258
Mobile: 416-529-9856
4711 Yonge Street,
Toronto | Ontario | Canada | M2N 6K8
