### ISSUE TITLE
uiapp.PostCommand() is not triggered in slave-graph

### ISSUE THREAD

**Issue by yueyingcui** [andydandy74/DynamoAutomation#22]
### Description
I'm trying to open the 'review warnings' window from Dynamo in the slave-graph. The slave-graph works great independently, but it seems can't trigger the postcommand() when run from the master-graph.

### Expected behaviour
- run then master-graph
- open Revit file
- run the slave-graph
- 'review warnings' window in Revit (not working, the window is not show up)
- close Revit file (works great without any error)

### My setup
- Operating System: windows 10
- Dynamo version: 0.9
- Revit version & build number: Revit 2016

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.x build of Dynamo (no dialy build)
- [x] I am using Revit 2015 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [x] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [x] None of the Revit models in my setup open with a warning
- [x] None of the Revit models in my setup open in a perspective view

Hi Andy,

Thanks advance for your help. If this DynamoAutomation is not the right tool for handling the postcommand, could you provide other suggestion?

My slave-graph python node

```
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import Revit elements
from Revit.Elements import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
import os
import System
from System import Guid
from System import Array
from System.Collections.Generic import *
from System.Collections.Generic import *
import time

doc = DocumentManager.Instance.CurrentDBDocument 
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#sec = 20
#time.sleep(sec)
		
def writeWarning(description):
	filepath = 'C:/warnings.txt'
	fh = open(filepath, "a")
	fh.write(description + "\n")
	fh.close()
	
		
def FailureProcessor(sender, e): # FailuresProcessingEventArgs 
	failuresAccessor = e.GetFailuresAccessor()
	failList = List[FailureMessageAccessor]()
	failList = failuresAccessor.GetFailureMessages()

	enumerator = failList.GetEnumerator()
	while enumerator.MoveNext():
		failure = enumerator.Current
		failID = failure.GetFailureDefinitionId()
		
		failureDescription = failure.GetDescriptionText()
		#Autodesk.Revit.UI.TaskDialog.Show("Catch Failure/Warning", failureDescription)
		writeWarning(failureDescription)


t = Transaction(doc, "Create new transaction") 
t.Start()

app.FailuresProcessing += FailureProcessor
id = RevitCommandId.LookupPostableCommandId(PostableCommand.ReviewWarnings)
binding = uiapp.CreateAddInCommandBinding(id)
uiapp.PostCommand(id)

t.Commit()
#time.sleep(sec)
writeWarning("done the hard work")

OUT = "Done"
```

Thanks,
Yueying

**Comment by andydandy74** [comment]
@yueyingcui Sorry for the late reply.
Not sure. Maybe calling some commands like PostCommand in journal mode does not work.
A possible alternative would be to modify the ```Journal.ByWorkspacePath``` node in such a way that it would create a journal file that would first launch Dynamo and run the slave graph and subsequently launch the ```ReviewWarnings``` command. 
Can you tell me more about your slave graph?

**Comment by yueyingcui** [comment]
Hi Andy,

Thanks for reply, and sorry for the delay too...

Sure, my slave graph contains only one Python node, and the content is in my previous comment. Yes, I am also thinking about PostCommand is not compatible with journal mode.

Is there other way to open Dynamo in Revit without using journal files? I have written some C# code to open Revit, but haven't figure out how to open Dynamo afterward without using journals.

Thanks,
Yueying

**Comment by andydandy74** [comment]
None that I'm aware of, sorry.

**Comment by yueyingcui** [comment]
sure, thanks for reply though :) I think the journal method just doesn't allow any pop-ups during the process...
