### ISSUE TITLE
Warning "JournalFiles.Cleanup" Node

### ISSUE THREAD

**Issue by aledarba** [andydandy74/DynamoAutomation#23]
### Description
Hi Andy!! I am trying to use your graph but I cannot make it work.

When I run it, a warning appears in my "Journal.Files.Cleanup" node saying the following statement:
"Warning: One or more of the input types are not matching. Couldn't find a version of __func_85066088161640b196e1c33e685c6948 that takes arguments of type (string,bool,int,Function)"

Do you know why? 

I have followed all your indications.

Thank you in advance. 

### My setup
- Operating System: ................
- Dynamo version: 1.2
- Revit version & build number: 2016 R2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.x build of Dynamo (no dialy build)
- [x] I am using Revit 2015 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [x] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [x] None of the Revit models in my setup open with a warning
- [ ] None of the Revit models in my setup open in a perspective view. 
Is a sheet a perspective??

**Comment by andydandy74** [comment]
@aledarba Sorry for the late reply, very busy these days.
Could you post a screenshot of what goes into your ```JournalFiles.Cleanup``` node?
Also, does the rest of the graph execute without issues?

**Comment by aledarba** [comment]
Hi @andydandy74 !! 
No problem at all, I finally found the solution and totally forgot to post it.

I solved it adding a new node: when I connect "Revit Version" node into "revitVersion" input of "Journal.ByWorkspacePath" node, the previous Warning appears.
I just added a "String.ToNumber" node between these two so I connect a number into "revitVersion" input. That's it.

The rest of the graph is working very well!! Thank you so much!!

**Comment by andydandy74** [comment]
Ah yes, I need to so something about this inconsistency.  ```Journal.ByWorkspacePath``` expects version to be an integer while ```RevitAddinsPath.ByVersion``` and ```RevitExecutablePath.ByVersion``` expect it to be a string. Thanks for reminding me.
