### ISSUE TITLE
Dynamo issues

### ISSUE THREAD

**Issue by AshTheGreat1** [andydandy74/DynamoAutomation#24]
Hi I have 2 questions.

1. If you have a campus style project with multiple central files. Let's say all the central file uses the same family. If the family is modified, is there any way that the family can be reloaded in all the files at once? Without opening each and every file one by one.

2. Can sheet set be PDF-ed or printed from multiple files without opening each and every one of them?

Thanks,
Ashique
Designer
WATG

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ yes] I am running the *latest* DynamoAutomation version
- [ yes] I am running a stable 1.x build of Dynamo (no dialy build)
- [ yes] I am using Revit 2015 or higher
- [ yes] I do not have multiple Dynamo versions installed on my system
- [ yes] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [ yes] None of the Revit models in my setup open with a warning
- [ yes] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
In both cases, I would say no. At least I don't know of a way of performing these operations without opening the project file. That is why I made this package. ;-)
