### ISSUE TITLE
Batch process - files are not saved

### ISSUE THREAD

**Issue by Gowwie** [andydandy74/DynamoAutomation#27]
### Description

I want to batch process revit files.

The Master graph seems to run fine in Dynamo studio: Revit starts, the slave graph is run. And i can see the changes made to the files. Then Revit is closed and nothing is saved.

The DynamoAutomate-nodes in the Master graph is supposed to save the files aswell? before closing. Or am i missing something? See my master graph below.

![test master](https://cloud.githubusercontent.com/assets/28555406/25837107/235625b2-348c-11e7-9447-99f56a51fedd.jpg)

[journal.0001.txt](https://github.com/andydandy74/DynamoAutomation/files/985655/journal.0001.txt)
[dynamojournalfile_1.txt](https://github.com/andydandy74/DynamoAutomation/files/985656/dynamojournalfile_1.txt)

### Expected behaviour

The Revit files should be saved automatically beforce closing.

### My setup
- Operating System: win 7 64bit
- Dynamo version: 1.3
- Revit version & build number: 2017 / 17.0.416.0 / 20160225_1515(x64)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [X ] I am running the *latest* DynamoAutomation version
- [X ] I am running a stable 1.x build of Dynamo (no dialy build)
- [X ] I am using Revit 2015 or higher
- [X ] I do not have multiple Dynamo versions installed on my system
- [X ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [X ] None of the Revit models in my setup open with a warning
- [X ] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
You'll need to add a node that saves the doc to your slave graph. Clockwork has nodes for saving and synching with central.

**Comment by Gowwie** [comment]
Thanks! I did not know that. Somehow i assumed the master graph-nodes took care of that.

It's almost working now... i want to change some parameters with the slavegraph before saving,
using the "passthrough"-node and "document.saveas". See slave graph below.

But the saving-part does not seem work with automatic/manual run. The parameters change and nothing more. But if i force it to run by unlink->relink a node it works and save the file.

Is there a better/standard method to save a file? I need to make sure all processing is done before saving. (I dont use workshare)

![question](https://cloud.githubusercontent.com/assets/28555406/26000601/e1b9309a-3729-11e7-84fc-49a0ab6f3883.jpg)

I'm new to Dynamo, if that was not abvious ;)

**Comment by Gowwie** [comment]
Update:
 Does not work even without the "passthrough". The SaveAs-node never runs on on its own.
 Only if i force it to run by unlink and relink a node in the graph.

But i see that SaveAs was in a bug-list "Nodes acting up in 1.3"?
 Should i just give up with the savingfunctionality of clockwork at the moment?

Thanks in advance for any info or hints in the right direction.
 /Gowwie

**Comment by andydandy74** [comment]
You are perfectly right, I had completely forgotten about that.
https://github.com/andydandy74/ClockworkForDynamo/issues/130
I'll try and have a look at that tonight...

**Comment by andydandy74** [comment]
@Gowwie - I updated the SaveAs node last night, but I don't think that was the problem.
Please try the following:
1. Replace these files in the DynamoAutomation package: https://github.com/andydandy74/DynamoAutomation/tree/master/package/dyf
2. Set the slave graph's run mode to Automatic

**Comment by andydandy74** [comment]
And going through the issues, I noticed that this is a known bug: #15

**Comment by Gowwie** [comment]
Hi, thanks for looking into it.

Not sure if this is a good method to respond, but my issue was closed.

My slavegraph is set to automatic, and I updated DynamoAutomation/Clockwork.
I tried the updated SaveAs-node, unfortunately i still have the same problem.

It wont save :/

Only by forcing it to run by relinking a node can I make it save.

/Gowwie


18 maj 2017 06:02:00 +02:00, skrev Andreas Dieckmann <notifications@github.com>:

**Comment by andydandy74** [comment]
Mmh. Can you open your slave graph in a text editor and make sure it says ```HasRunWithoutCrash="True"``` at the end of the first line?

**Comment by Gowwie** [comment]
Yes, its set to true, and runtype automatic.

"<Workspace Version="1.3.0.875" X="-1850.16232352307" Y="112.597876317505" zoom="0.86355032761428" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">"

**Comment by andydandy74** [comment]
Running out of ideas here. Can you share your master and slave graphs?

**Comment by Gowwie** [comment]
Sure thing, here it is.

Master and two different slave graphs for testing.

[Graphs_Gowwie.zip](https://github.com/andydandy74/DynamoAutomation/files/1010394/Graphs_Gowwie.zip)

**Comment by andydandy74** [comment]
No, that's perfect. I'll try to find some time tonight for testing it.

**Comment by Gowwie** [comment]
It seems to be working now. When the following lines are added in the SaveAs script:

```
from RevitServices.Transactions import TransactionManager
trans = TransactionManager.Instance
trans.ForceCloseTransaction()
```

I'm new to this, but it seems to force the graph to run automatically. Finally!

**Comment by andydandy74** [comment]
Interesting - I tried the same thing last night but coul *not* get it to run.

**Comment by andydandy74** [comment]
This issue should be fixed with the next release of DynamoAutomation.
