### ISSUE TITLE
Dynamo 1.3

### ISSUE THREAD

**Issue by aledarba** [andydandy74/DynamoAutomation#28]
### Description
Hi @andydandy74 ,

I am about to update my Dynamo version and before that, I wanted to verify that everything is working as expected in Dynamo 1.3. 
I am currently working well with DynamoAutomation and I would like to keep my graphs working. 

Thank you so much. 
By the way, I am not sure if I should post the doubts here in "Issues", but I don't know the proper place.

### My setup
- Operating System: ................
- Dynamo version: ................
- Revit version & build number: ................

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *latest* DynamoAutomation version
- [ ] I am running a stable 1.x build of Dynamo (no dialy build)
- [ ] I am using Revit 2015 or higher
- [ ] I do not have multiple Dynamo versions installed on my system
- [ ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [ ] None of the Revit models in my setup open with a warning
- [ ] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@aledarba As long as you're on Revit 2016 it should work.
You'll need to download the latest version from the Package Manager as some of the custom nodes in the package weren't processing file paths correctly in 1.3
Also, please note that the Journal.ByWorkspacePath node now has a fourth input ```revitVersion```. Unlike the other nodes in a typical master graph it expects the version number as an integer, not a string.
I've just updated one of the sample files to reflect that change:
https://raw.githubusercontent.com/andydandy74/DynamoAutomation/master/samples/master_graphs/Scenario_A1.dyn
