### ISSUE TITLE
DynamoCLI.exe error and multiple Dynamo batch-processes

### ISSUE THREAD

**Issue by martinromby** [andydandy74/DynamoAutomation#36]
### Description
I have a working Dynamo Automation process working with master- and slavegraphs.
I'm now trying to use .bat file to execute DynamoCLI.exe for later use of Windows Task Manager. 

When I run the batch file I get this error / warning from DynamoCLI.exe. 
![2017-07-21_1219](https://user-images.githubusercontent.com/15892140/28460848-383d4eee-6e14-11e7-85c0-79db05e12ae0.png)

The DynamoSandbox.exe runs succesfully on the first model but then stops.
Since I couldn't find any documentation on the directories on DynamoSandbox.exe and DynamoCLI.exe after the introduction of the Core and Revit folder structures, I simply copy / pasted the DynamoSandbox.exe into C:\Program Files\Dynamo\Dynamo Core\1.3, where the DynamoCLI.exe is located. Maybe I'm wrong about this, but havn't been able to find documentation on this.

Anyone having the same problems?

**The .bat file:**
@echo off 
echo This is an example for calling multiple Dynamo batch-processes...
:: Change to Dynamo's working directory
cd C:\Program Files\Dynamo\Dynamo Core\1.3
@echo on
:: List all calls to the DynamoCLI below...
:: Make sure to call them with the /W option in order to execute them successively
start /W DynamoCLI.exe -o "C:\temp\DynamoAutomation\master_graphs\AutomationDynaSlackWarnings.dyn"
@echo off 
echo All done...
:: Use the pause command to keep the window from closing automatically
pause

### Expected behaviour
I would expect DynamoCLI.exe to run mastergraph successfully without any warnings / errors. 

### My setup
- Operating System: Windows 10 pro x64
- Dynamo version: 1.3.1
- Revit version & build number: **18.0.2.11** | **20170525_2315(x64)** | **2018.0.2**

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running the *latest* DynamoAutomation version
- [x ] I am running a stable 1.x build of Dynamo (no dialy build)
- [x ] I am using Revit 2015 or higher
- [x ] I do not have multiple Dynamo versions installed on my system
- [x ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [x ] None of the Revit models in my setup open with a warning
- [x ] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@martinromby - I encountered similar issues with the DynamoCLI recently but haven't followed up on it yet.

**Comment by martinromby** [comment]
@andydandy74 - thank you for the reply. Do you think it has anything to do with the fact that I simply copy / pasted the DynamoSandbox.exe into C:\Program Files\Dynamo\Dynamo Core\1.3, where the DynamoCLI.exe is located? Or is this correct?

**Comment by andydandy74** [comment]
@martinromby Don't think so. I didn't copy the Sandbox.exe and got the same behaviour.

**Comment by andydandy74** [comment]
@martinromby - So I had another look at this. 
Lookig at the resulting journal file, it seems that when running a master graph through the CLI, the startup argument for Revit (i.e. the generated journal file) is treated like a Revit model that's dragged onto Revit:
```
Jrn.Command "Internal" , "Open an existing project , ID_REVIT_FILE_OPEN"
 'H 11-Aug-2017 20:07:26.548;   0:< 
 Jrn.Data "File Name"  _
         , "IDOK", "..\..\..\..\..\..\..\..\temp\DynamoAutomation\output\DynamoJournalFile_1.txt"
```
I don't think this is going to be resolved any time soon... :-(

**Comment by andydandy74** [comment]
@martinromby - While this doesn't fix the orginal issue, I did manage to find a workaround.
Basically what you need is to have a master graph that does **not** use the ```Process.ByPathAndArguments``` node. 
Instead, your master graph needs to create a batch file of its own that will start the required Revit sessions by itself. 
I've added a new sample that illustrates how this works (Scenario_A1_SchedulableWithConfig.dyn). 
If you copy the 1.x samples to C:\temp\DynamoAutomation and run C:\temp\DynamoAutomation\misc\BatchFileExample.bat you can see it in action.

**Comment by martinromby** [comment]
@andydandy74 Sorry for the late reply. 
I've tested according to your instructions and it's working! Thanks a lot.

**Comment by GAnagno** [comment]
works like a charm
