### ISSUE TITLE
Nodes missing in version 1.3.3

### ISSUE THREAD

**Issue by martinromby** [andydandy74/DynamoAutomation#38]
### Description
It seems that when setting up a new Dynamo installation with the latest version of DynamoAutomation package, some nodes are missing, i.e Process.ByPathAndArguments, Journal.PurgeModel, Journal.PurgeModels + more. 
These nodes seems to be used in the updated sample files, which properly means they still should be in the package.
The nodes can be found in DynamoAutomation 1.3.2 

DynamoAutomation 1.3.3
![2017-08-17_1223](https://user-images.githubusercontent.com/15892140/29408420-65fe5cc6-8348-11e7-9d0b-f5c00f44a002.png)

DynamoAutomation 1.3.2
![2017-08-17_1221](https://user-images.githubusercontent.com/15892140/29408421-66035c8a-8348-11e7-8229-845a1ab41fee.png)

### Expected behaviour
I would expect that these nodes would be installed in the 1.3.3 installer. 

### My setup
- Operating System: Windows 7 pro x64
- Dynamo version: 1.3.1
- Revit version & build number: 18.0.2.11 | 20170525_2315(x64) | 2018.0.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.x build of Dynamo (no dialy build)
- [x] I am using Revit 2015 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [x] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [x] None of the Revit models in my setup open with a warning
- [x] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@martinromby Can you check if the bin subfolder of the package contains a file called DynamoAutomation.dll ?

**Comment by martinromby** [comment]
DynamoAutomation.dll is in the bin folder @andydandy74 

![2017-08-17_1343](https://user-images.githubusercontent.com/15892140/29410728-2c72f764-8352-11e7-89d4-9df3d8d793a2.png)

**Comment by andydandy74** [comment]
In that case try unblocking the DLL. (You should find information on that on the forum...)

**Comment by milotindragos** [comment]
Hey,
There are a couple of errors appearing in the install in both version 1.3.3 and 1.3.2.
In 1.3.3 there are 2 missing nodes (yes I did unblock the dll).
And in version 1.3.2 I can find the 2 missing nodes but another is now missing. 
![2017-08-18_03-37-14](https://user-images.githubusercontent.com/30367360/29443104-bebd2b14-83cd-11e7-8fe8-e1fdb807f415.png)
![2017-08-18_03-49-44](https://user-images.githubusercontent.com/30367360/29443103-bebcda92-83cd-11e7-8307-06737f304795.png)
![2017-08-18_04-24-19](https://user-images.githubusercontent.com/30367360/29443105-bebe25f0-83cd-11e7-99d7-2901935202b3.png)

**Comment by andydandy74** [comment]
@martinromby Okay, I can reproduce this behaviour on my machine and unblocking the DLL in Dynamo 1.3.0 or 1.3.1 won't help (it does in 1.0.0 - but DA isn't compatible with that Dynamo version). I'll try to investigate this further this weekend.

**Comment by milotindragos** [comment]
Hey @andydandy74 just a follow-up on this. I managed to make it work but in a strange way. 

What I did is: I forked DynamoAutomation opened it in Visual Studio via the GitHub extension, rebuilt it and replaced the files in the package. It still did not work.. but wait for it. Because of a different task I had to restart my computer and opened Revit 2016 and out of curiosity opened the Master Graph there and now I could see all the Nodes. Nothing was missing anymore. I then opened Dynamo Sandbox with Administrative rights and now it is working. 
This will change everything in regard to Revit workflow. 

I now have another problem:
![2017-08-18_15-12-15](https://user-images.githubusercontent.com/30367360/29463029-23e71080-8429-11e7-95a1-b2c320ad9c58.png)

**Comment by andydandy74** [comment]
@martinromby @milotindragos - There is a new version of DA on the package manager. Please upgrade to that version and let me know if that fixes the problem of missing nodes.

**Comment by martinromby** [comment]
@andydandy74 The 1.3.4 version seems to include the necessary nodes. Issue is solved. 
![2017-08-21_1137](https://user-images.githubusercontent.com/15892140/29513314-37128a7a-8665-11e7-8502-3103cfa9f0a4.png)

**Comment by andydandy74** [comment]
Glad to hear it. Many thanks to @dimven for pointing me in the right direction.

**Comment by milotindragos** [comment]
@andydandy74 the new version works perfect. From the tests I did it has all the nodes and everything seams to work now. Thank you
