### ISSUE TITLE
Batch processing folder of RFAs fails to complete all files in folder.

### ISSUE THREAD

**Issue by GMcDowellJr** [andydandy74/DynamoAutomation#41]
### Description
Processing a series of RFA files in a single folder with one slave graph (changing fonts). The folder has 79 files but the process hangs after 60 files or so. RAM doesn't appear to have increased to a point where I'd expect a memory error. The drive it's writing to isn't full. Shutting down Revit from the Task Manager (need to shut down multiple instances quickly before another starts) and restarting from where it left off doesn't work either. The only way I've found to continue where it left off is to restart the computer entirely.

### Expected behaviour
I would expect the graph to complete all files in the folder.

### My setup
- Operating System: Windows 10 Pro
- Dynamo version: 1.3.1
- Revit version & build number: 2016 - Update 7 for R2 - 16.0.1185.0 - 20161004_0715(x64)

[FixStandards.zip](https://github.com/andydandy74/DynamoAutomation/files/1249671/FixStandards.zip)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [X] I am running the *latest* DynamoAutomation version
- [X] I am running a stable 1.x build of Dynamo (no dialy build)
- [X] I am using Revit 2015 or higher
- [X] I do not have multiple Dynamo versions installed on my system
- [X] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [X] None of the Revit models in my setup open with a warning
- [X] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@GMcDowellJr As a first workaround for not having to restart your machine, try terminating the DynamoSandbox.exe process first. That will prevent new instances of Revit.exe spawning. 

I'm curious about something you wrote, though:

> need to shut down multiple instances quicklyneed to shut down multiple instances

Are you saying there are multiple instances of Revit.exe open at the same time?

**Comment by GMcDowellJr** [comment]
There are multiple instances of Revit open... the first is the one I'm running Dynamo from, the second is the instance running the journal files. I read something on the Wiki about running through the sandbox but I didn't know how to do that and this seemed to be working -- although I guess we can safely say it's not working... ;) Consequently, there is no DynamoSandbox.exe process running.

**Comment by GMcDowellJr** [comment]
Well... now I feel stupid -- first time I went looking for the sandbox I found something that was command prompt based - now I see the same interface as Dynamo Revit - Let me try it from there and report back.

**Comment by andydandy74** [comment]
Ah interesting. Never tried running the master graph from Revit before. This could indeed be what's causing it. Will wait for your feedback.

**Comment by GMcDowellJr** [comment]
Same issue. It gets through 60 of the 79 and hangs. Most of these files took 30-45 seconds to open, process, and save. I'm not at 6 minutes on the 61st file.

Closing the sandbox and starting over where it left off (no restart this time) produced one more successful file and then hangs again with the Revit.exe process _Running_ but no screen displayed. Ending that Revit process manually starts a new process but it sits at _Not responding_ for quite a bit.

**Comment by andydandy74** [comment]
if you divide you files into two folders of 40 each, will they process okay?

**Comment by GMcDowellJr** [comment]
I haven't tried that. What does the Master-Graph look like?

**Comment by andydandy74** [comment]
It's the same. You just run it twice, once on each folder. I'd like to see if the issue is caused by the number of files or one specific file. If it's a specific file, we can start examining journal files. I've successfully used DA with a significantly larger number of files in the past, so I'm hoping the issue is being caused by one specific model.

**Comment by GMcDowellJr** [comment]
Sorry for the delay. Back into again and the first round had the same issues. Trying again (after a restart) with several folders but one Master Graph. 49 files in the first folder completed, and 13 in the next (out of 110) before it stopped. These are different files than before.

**Comment by andydandy74** [comment]
Can you run over the second folder separately?

**Comment by GMcDowellJr** [comment]
So I'm not going backwards with the work I need to do, how about I run it again with 2 different folders/sets of files? I'm pretty sure, based on what's happening, I'll get the same response.

**Comment by andydandy74** [comment]
I'd just like to rule out the possibility that this is caused by something in a particular model. If you know which file was the last that did not get processed, it would be enough to put that file in a folder and run it again and see if that works. Once we've established that models are not to blame I am happy to start running tests on my end, too.

**Comment by GMcDowellJr** [comment]
running it now - pretty sure it's not file specific, however, as it has happened over several differ runs with different files being the last one run

**Comment by GMcDowellJr** [comment]
It ran for a lot longer this time than it has before. I went through 4 folders worth of content (maybe 20 or so in each) before it finally stopped. The attached file "CTrayFit_Wire+Basket_Horizontal+Cross_Round+Wire_Stainless+Steel_Hubbell" was the last one to complete, and the "CTrayFit_Wire+Basket_Horizontal+Tee_Flat+Style+Wire_Hubbell" would have presumably been the next file to process.

[DynamoAutomation Files.zip](https://github.com/andydandy74/DynamoAutomation/files/1286060/DynamoAutomation.Files.zip)

**Comment by andydandy74** [comment]
@GMcDowellJr Sorry for the long delay. I cannot reproduce this behaviour. I started running your scripts on my library and for the last 90 minutes or so it has been processing families and is still going after 160+ rounds. If you are still interested in getting to the bottom of this, the next step we would need to take is looking at journal files.

**Comment by GMcDowellJr** [comment]
I figured it was something on my end. If I run another batch over multiple folders, and send you that journal file, will that be enough as a start?

**Comment by andydandy74** [comment]
Yes. What I will need is the last journal file that was created by Revit (not DynamoAutomation) in C:\ProgramData\Autodesk\Revit\Addins\2016. And maybe best to include the one before it as well so I have a comparison.

**Comment by GMcDowellJr** [comment]
Here are the last several files. Including a worker logs if they're important.
[journal files.zip](https://github.com/andydandy74/DynamoAutomation/files/1331002/journal.files.zip)

**Comment by GMcDowellJr** [comment]
BTW, should I be able to work in another instance of the same Revit release as the one the scripts are running on?

**Comment by andydandy74** [comment]
Never tried it, but I don't see why not

**Comment by andydandy74** [comment]
From the looks of it, Revit hangs halfway into the loading of the addins. Please try either of the following:
A) disable the Screencast addin (temporarily renaming the*.addin filetype will do) and run another batch operation 
B) do the same for the Metamorphosis addin.
Your journal files end before Revit actually goes into journal playback mode. While Metamorphosis seems to be registering okay, it may be that starting the app causes Revit to hang. My money is on Screencast, though, since that app never registers in the two broken runs you sent me.
If the issue persists despite disabling either addin please send the appropriate journal files although I'm doubtful that we will find a solution in that case.

**Comment by GMcDowellJr** [comment]
Thanks, Andreas. I appreciate the look. I'll let you know how it works out.

**Comment by GMcDowellJr** [comment]
Looks like that did the trick! Thanks again!

**Comment by andydandy74** [comment]
So which one was it? Or did you disable both at the same time?

**Comment by GMcDowellJr** [comment]
I did both. I’ve got more to do though, so I’ll turn them on one at a time and let you know.

**Comment by GMcDowellJr** [comment]
BTW, looks like it was the Screencast addin... or at least in part. Same thing happened recently but I didn't have Metamorphosis installed and renaming the Screencast addin got me past the issue.
