### ISSUE TITLE
Slave scripts not running

### ISSUE THREAD

**Issue by jtotheb86** [andydandy74/DynamoAutomation#43]
### Description
I have used your scenario C master script to open families, run DYN process on them, save and close.
I have frozen the filepath nodes to do with the project as I don't need to load them anywhere.
It opens the files, hangs for a bit, saves and closes. It doesn't seem to run the script. My script works if I open the family and run manually from within dynamo in revit.

### Expected behaviour
Run DYN script when opening family

### My setup
- Operating System: Windows 10
- Dynamo version: - 1.3.1
- Revit version & build number: 2016 - 16.0.1185.0
### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [X] I am running the *latest* DynamoAutomation version
- [X] I am running a stable 1.x build of Dynamo (no dialy build)
- [X] I am using Revit 2015 or higher
- [X] I do not have multiple Dynamo versions installed on my system
- [X] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [X] None of the Revit models in my setup open with a warning
- [X] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
@jtotheb86 So you're saying the families are opened one by one but the script doesn't seem to run? In that case I'll need to see your slave graph. Can you upload it here? If you need it to be confidential you can send it to andreas at badmonkeys dot net instead.

**Comment by jtotheb86** [comment]
@andydandy74 sorry i've just realised that my script isn't performing correctly, it is saving the family before performing the operations. I had only tested before adding the document.saveas node

If you can have a look that would be much appreciated

[SetActiveView.zip](https://github.com/andydandy74/DynamoAutomation/files/1262352/SetActiveView.zip)

**Comment by andydandy74** [comment]
This graph looks okay to me.
I can't test it exactly like it is because I don't have two of the custom nodes  (Get All Views and Visual Style Select). Also, I don't have Revit 2016 on the computer I'm travelling with.
BTW, in Revit 2016 you should not need the KillCurrentProcess node.
Does this graph work when you run it manually (including saving the family)? If saving doesn't work, it may be because the Document.SaveAs node may have some issues under Dynamo 1.3 (see https://github.com/andydandy74/ClockworkForDynamo/issues/130). I have recently made some changes to the node but haven't tested them properly yet. You can download the current version here:
https://raw.githubusercontent.com/andydandy74/ClockworkForDynamo/master/nodes/1.x/Document.SaveAs.dyf
But as I said I haven't tested this node properly under 1.3 yet.

**Comment by jtotheb86** [comment]
cheers, yeh I realised about the kill afterwards and just left in in there for the 2017 version and changed to false for 2016.

The graph runs, does everything, but seems to save before completing the beginning of the script. Its like the Set Active View python is running last. That python script has run because the view changes in revit, but the saved file doesn't have the changes.

I've just downloaded the updated node and is still performing the same. I don't think its a problem with your nodes as they are working. It must be something to do with the python script for changing the active view

**Comment by andydandy74** [comment]
So you're saying the family doesn't get saved with the changed view even when the script is run in Manual mode?
Perhaps try closing all other opened views at the end of the Python script.

**Comment by jtotheb86** [comment]
yes, when run in manual mode the file saves, but not on the changed view

can you assist with the code for closing the non active views? my python knowledge is minimal

**Comment by andydandy74** [comment]
I can point you in the right direction:
Getting all opened views: http://www.revitapidocs.com/2017/1ac8b262-9085-07e9-cef6-85377e8c70f3.htm
Closing a view: http://www.revitapidocs.com/2017/c60046d1-6fbd-6fc1-6f09-0aecdb3a7fe9.htm
For further assistance with your Python script, please make use the Dynamo forum

**Comment by jtotheb86** [comment]
Thanks very much for your help!
