### ISSUE TITLE
Workarounds for white space?

### ISSUE THREAD

**Issue by DanBoghean** [andydandy74/DynamoAutomation#44]
### Description
All of our project revit files are in folders that contain white space, thus reducing the capability of DynamoAutomation.

### Expected behaviour
It would be great if there was some workaround to deal with white spaces in directory names.

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.1
- Revit version & build number: 2017.2 Build 20170118_1100

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.x build of Dynamo (no dialy build)
- [x] I am using Revit 2015 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [x] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [x] None of the Revit models in my setup open with a warning
- [x] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
Sorry, nothing I can do about it. Unfortunately, that's one of the limits of Revit journals.

**Comment by dimven** [comment]
Hi,

Not sure if this will work, but you could try setting up a junction point to a folder:
https://en.m.wikipedia.org/wiki/NTFS_junction_point

**Comment by andydandy74** [comment]
@DanBoghean If you try @dimven 's suggestion could you please report back whether that has solved your problem? In that case I would add it to the DynamoAutomation wiki.

**Comment by DanBoghean** [comment]
Unfortunately it doesn't seem like I have the proper permissions to do this. I'll have to take to IT and see if I can get it set up, but it might be a while. 

I'll keep you updated once I get around to trying it. Thanks!
