### ISSUE TITLE
Journal.ByWorkspacePath

### ISSUE THREAD

**Issue by alexberd** [andydandy74/DynamoAutomation#55]
### Description
Node Journal.ByWorkspacePath does not create a journal file for Revit to run according to the Dynamo Version. I currently have dynamo version 1.3.2.2480, however the journal file created by this node includes the following (dynamo version 1.3) which creates a Journal error during "play":

Jrn.RibbonEvent "Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%Visual Programming%Dynamo 1.3:Dynamo.Applications.DynamoRevit"

### Expected behaviour
Node Journal.ByWorkspacePath should create a Journal file with the correct Dynamo version or at least should give the user an option to input the correct Dynamo version.

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.2.2480
- Revit version & build number: 16.0.1063.0 20151007_0715(x64) R2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *latest* DynamoAutomation version
- [ ] I am running a stable 1.x build of Dynamo (no dialy build)
- [ ] I am using Revit 2015 or higher
- [ ] I do not have multiple Dynamo versions installed on my system
- [ ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
- [ ] None of the Revit models in my setup open with a warning
- [ ] None of the Revit models in my setup open in a perspective view

###Attached Journal File
[journal.0001.txt](https://github.com/andydandy74/DynamoAutomation/files/1890133/journal.0001.txt)

**Comment by andydandy74** [comment]
Can you attach the journal that contains the error?

**Comment by alexberd** [comment]
Many thanks for your answer Andy! I am attaching the Revit journal file.( [journal.0001.txt](https://github.com/andydandy74/DynamoAutomation/files/1890133/journal.0001.txt) ) Please have a look. Any help will be really appreciated. Running dynamo, Revit opens and a "journal error" message appears, "The journal file could not be run to completion. Utilize care in saving any work as the project may be in an unstable mode". Then I have to press "Enter interaction mode" where journal files stop to run.

I also noted that even if I change the 
`Jrn.RibbonEvent "Execute external command:CustomCtrl_%CustomCtrl_%Add-Ins%Visual Programming%Dynamo 1.3:Dynamo.Applications.DynamoRevit" ` 
line to
`Jrn.RibbonEvent "Execute external command:CustomCtrl_%CustomCtrl_%CustomCtrl_%Add-Ins%Dynamo Version%versions%Dynamo 1.3.2.2480:Dynamo.Applications.Command1"`

Revit opens normally, however, all dynamo nodes which need Revit api transactions do not work. 
The following message appears to these nodes:

> "Warning: ElementQueries.OfCategory operation failed. 
> Starting a new transaction is not permitted. It could be because another transaction already started and has not been completed yet, or the document is in a state in which it cannot start a new transaction (e.g. during failure handling or a read-only mode, which could be either permanent or temporary).
> 
>

**Comment by alexberd** [comment]
Hi Andy, I just checked that in Revit 2018 the Revit api transactions work fine in Dynamo. It is only a Revit 2016 issue of the journal file when it opens dynamo as an external application:

> Warning: ElementQueries.OfCategory operation failed. 
> Starting a transaction from an external application running outside of API context is not allowed.

**Comment by andydandy74** [comment]
@alexberd According to your journal you also have Dynamo 0.9.1 installed. This won't work. See installation requirements (https://github.com/andydandy74/DynamoAutomation#requirements).
