### ISSUE TITLE
wont run script 

### ISSUE THREAD

**Issue by walid-el** [andydandy74/DynamoAutomation#56]
### Description
hello, i have a bunch of central files that been moved am using a dynamo script to save them to new location, the scripts work fine on dynamoplayer but on  the master graph.
revit open and shut down without runing the script, 

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.x build of Dynamo (no dialy build)
- [x] I am using Revit 2015 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [ ] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces
**### - [ ] None of the Revit models in my setup open with a warning** i do 
- [x] None of the Revit models in my setup open in a perspective view

**Comment by andydandy74** [comment]
Hi @walid-el 
Let's start off with a couple of questions:
1. Which Revit version?
2. Which Dynamo version?
3. Can you share your journals?

**Comment by walid-el** [comment]
hello Andy, 
please find the journal attached, 
am running Revit 2017.2 and Dnamo 1.3.3
[Dynamo_Journal_File_1.txt](https://github.com/andydandy74/DynamoAutomation/files/2179986/Dynamo_Journal_File_1.txt)

the files am trying to process are;  revit central files which have been moved from original path, here is the starting dialog box 
![error](https://user-images.githubusercontent.com/40629970/42505411-982bacfe-8436-11e8-91b7-42a9b8db0a3a.JPG)
i am guessing this is the issue, since dynamo addin wont start unless revit is lunched !? no !

**Comment by andydandy74** [comment]
Yes, that would be the issue and apparently debug mode isn‘t helping here. It may be possible to add an additional option to circumvent this. I‘ll see if I can find some time to to investigate this during the weekend.

**Comment by walid-el** [comment]
thank you Andy,

**Comment by andydandy74** [comment]
@walid-el - Unfortunately I see no way of circumventing this message. Waht should work, though, is to have Revit open the model detached. You will need DA v1.31.1 vor that.

**Comment by walid-el** [comment]
thank you andy, will try something with the detached and see how it goes,

On Wed, Jul 11, 2018 at 8:33 AM, Andreas Dieckmann <notifications@github.com
