### ISSUE TITLE
Disable multiple dynamo versions

### ISSUE THREAD

**Issue by laurenskruger** [andydandy74/DynamoAutomation#59]
Hi Andreas,
I'm looking forward to testing the automation tools on dyn 1.3 for revit 2016 today. Your notes specify that only one version of dynamo can be installed but
I also have a copy of dyn 2.0 for revit 2018.

Is there a quick way to disable dyn 2.0 without the need to completely uninstall?

It's my first time posting on github so please let me know if I've submitted this query in the wrong place.

Thanks. 
Lauren

**Comment by andydandy74** [comment]
@laurenskruger - I don't know of a quick way to disable Dynamo 2 in the version selector.
I keep separate branches in a virtual machine for testing stuff in both Dynamo versions independently.

**Comment by laurenskruger** [comment]
Hi Andy,
So I've finally got a chance to test Scenario 4 using Dynamo 2.0.1.
It worked!! Kinda :/

I found the first model would remain open & I had to close revit before the next model would open.. and so on.
Should I add a document.close node to my slave graph?
Is there something I'm missing? 

I'd like to run this on the entire office family library - hundreds of files at a time. It will be pretty rough to close the file & wait for the next to load for so many files.

Its the first time I've used your package & its all a little over my head so your help will be much appreciated. 

Thanks!

**Comment by andydandy74** [comment]
Sounds like your slave graph is missing the piece that will terminate Revit. Have a look at this:
https://github.com/andydandy74/DynamoAutomation/wiki/Slave-Graphs#difference-between-revit-2016-and-earlier-and-revit-2017-and-later
Also, if you're planning to batch-process families you might want to look into opening families in the background. That way you won't need to start a new Revit session for each family. The Rhythm package has a node for that: http://sixtysecondrevit.com/2016-11-07-open-revit-files-in-background-with/

**Comment by laurenskruger** [comment]
Thanks so much for the prompt advice. 
I'll check it out sometime this week and let you know how it goes. 

Really appreciate your help

**Comment by laurenskruger** [comment]
That did it! 
Huge thank-you. 
I was able to terminate revit for dynamo automation. 
I also worked out how to use the background open node which is far superior for the bulk action. 

My detail compenent families all have a new set of standard detail item subcategories now. 
Thanks to your nodes & guidance!!
