### ISSUE TITLE
Access to the path Denied in Journal.ByWorkspacePath

### ISSUE THREAD

**Issue by MShelp** [andydandy74/DynamoAutomation#60]
**Describe the bug**
when using  Journal.ByWorkspacePath I get the following error "Access to the path 'C:\ProgramData\Autodesk\Revit\Addins\2018' is denied." I have verified that I have write access to the folder and tried inputting other directories to JouralFilePath and all will say access denied.

Any help with this would be greatly appreciated. 

**Steps to Reproduce**
connected individual file paths to Revitfilepath and WorkspacePath with RevitAddinsPath.ByVersion and tried different combinations of the other inputs.  

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: Windows 10
- Dynamo version: Core: 1.3.4 Studio: 1.3.0
- DynamoAutomation version: 1.31.1
- Revit version: 18.3.1.2

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest* DynamoAutomation version
- [x] I am running a stable 1.3.x build of Dynamo (no daily build)
- [x] I am using Revit 2017 or higher
- [x] I do not have multiple Dynamo versions installed on my system
- [x] No folder or filename for any Dynamo graph or Revit model in my setup contains whitespaces or special characters
- [ ] Creating the journal files with debug mode enabled did not resolve my problem

**Comment by andydandy74** [comment]
@MShelp Where do you get the error? In the master graph?

**Comment by MShelp** [comment]
Yes, In the master.

**Comment by andydandy74** [comment]
Have you tried running DynamoSandbox in Admin mode?

**Comment by MShelp** [comment]
Yep. I've tried that.

**Comment by MShelp** [comment]
Hr

**Comment by MShelp** [comment]
Hello Andy, I Figured out the issue; I was feeding the node a directory instead of a file path. it is working now.
